name: Events Demo 1
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the workflow'
        required: true
        default: 'Demo 1'
      version:
        description: 'Version of the workflow'
        required: true
        default: '1.0.0'
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."